version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Optional: Group updates to reduce PR noise
    groups:
      github-actions:
        patterns:
          - "*"
    # Optional: Add reviewers
    reviewers:
      - "ukohae"
    # Optional: Add labels
    labels:
      - "dependencies"
      - "github-actions"