name: Convert Actions to SHA

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Convert to SHA
        run: |
          grep -rh "uses:" .github/workflows | \
            grep -v "department-of-veterans-affairs" | \
            grep -v "#" | \
            sed 's/.*uses: *//' | \
            grep "@" | sort -u | \
          while read action; do
            repo=$(echo $action | cut -d@ -f1)
            tag=$(echo $action | cut -d@ -f2)
            [[ "$tag" =~ ^[0-9a-f]{40}$ ]] && continue
            sha=$(git ls-remote https://github.com/$repo.git refs/tags/$tag | awk '{print $1}')
            [ -z "$sha" ] && continue
            echo "Converting: $action → $sha"
            find .github/workflows -name "*.yml" ! -name "convert-actions-to-sha.yml" | \
              xargs sed -i "s|uses: $action|uses: $repo@$sha # $tag|g"
          done

      - name: Create PR
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          commit-message: "feat: Pin external actions to SHAs"
          title: "Pin external GitHub Actions to SHAs"
          body: "Converts external actions to SHA pins. Dependabot will maintain updates."
          branch: feat/pin-actions-to-sha